age_keys:
    release:
        github_secret_name: ENC[AES256_GCM,data:MqDML1EtFxf5y8qiLSpiqreM6+k=,iv:J1TkbmTCUQP/IwMUkJwWWl8C4KqSJrrQQLDXDn+2t80=,tag:j9V8Cp0jzYFJIRdLfKlKxw==,type:str]
        private_key: ENC[AES256_GCM,data:umG8y0AbYYcOaIFpLYE0HlOx1PdXuuiiQ5tu+R9FUtHKBrEfGTn8d8JUkzxytP8KGnoNorUaoLsjlBbVFGWf1EVjs4mD1hpwX/4=,iv:M+dWJyZvdkB0O9iKuTMAd3Q7egtWL3+eefDj8JQKpQI=,tag:QLkXXLuimoGaM1X7uKxXGQ==,type:str]
    publish:
        github_secret_name: ENC[AES256_GCM,data:zkFgQw2yQb+8yjpWx7ftrwBXs/Y=,iv:QVp9x2kJjoIExflRrFfC3pEnKJUm9Mua3K5kUz/Q+g0=,tag:rw8w0eL7aTq9T4BRvudX9g==,type:str]
        private_key: ENC[AES256_GCM,data:5XLbgFhlzv42jQNw7FUeK1UT9qTmVakSVMgfUhDGHqPwgMbRaBaJdIlgtO465EhsCM/YEcBLVFMuGkJVbpiQHgqRJILPZCT7P8M=,iv:9iqf2OOs4Tm6jUqMLiyyO3tDms7vd9K33GZb8yUx0ZY=,tag:I0gMBFw58efP1Bt7m2fCnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBVdzhk
            TGJ3dXpzOW5kSGw0bGRTanFpcThhbWV6WTAwc0huOTFnV2dGWVdBCm1aRUg1R2Fz
            Vmx2Sm84Zi9aY1FHdktya1NieUJUSDdDb0lWS054RjFXUTgKLS0tIHNjNHkrTGNS
            NGlVZXJUSWlCQUJyZzZ0MER5c0VpSW5wSXNibmZmZVpnOU0K7WrLLPSaWYYgmeVs
            7MzpLOfgkizaG9bXfOePk+gqH9VKaIeBHjLRbH4nWrETlL/QuBIYb3vw9jyJ+46h
            unpq/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
    lastmodified: "2026-06-18T12:15:33Z"
    mac: ENC[AES256_GCM,data:uLNnKevCBRMIud2dL0OHZYHReM35RgZmfleaogqRUmSLqsHfGBtd+yIFJm0X3YjlTd2lXRPSGqLpiIGJKHYnWhCkl4k+OClfQhLrryH26MXbndNck5lB4PDCFkVBvo8DCIG9GmUXjyhKBotF6Eiq14TV98nYnVxjGI0Mn5n0lus=,iv:GmrqQqaB0D84zsCHWvKVxwRJzbldGUzmCJQZV1flU9s=,tag:xl0nnzW1mvhNunFbpr245A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
