git_signing:
    private_key: ENC[AES256_GCM,data:kZVMpE8AI4jUni+MErV5ntxrfn3QnP5fiY5rWp8bDlsqpzWTGH8yf+O00uqa3DoSkwK1jS1EczKufQmALhznbVi/wLZRzvjTRxWu5EqcCE1rMavPHN9v3zqjKMcX4p4NwJp8lZWWvKeiqHrW15LPXjKdIh0xSSV0Mo+wVC9LzJNjpn80REvm0S6NMRg+YmCW2q+2TyoWWeQL3r5/Jsa1ttcVq7XhxtqC0BtiVCRBxi2pSBlXQ0kosvPPmoW+EqaewI56FskBPcfjmRtdtoyxzRiAQvfEnjXw3rm69VYJpyhci2lOdrKuc8IYPscvhy6PBcfw9L8urGhqO1GaPCt/Qc7DhtkdTrcYR86XelCPaLxsYbYVCuStI/yTUBH47iCDta1/AQeOE7WGrGMpTWWxxp/i5w8TxXdOMcC49yYpEt6ftZoinlvLMG9BwTueeSXfTyEVWFRFovLmx3i8EcN6/DFJWPMX7cgQSB83HN7rSeAym3amrpBMXG1wF7i+ni1/iuGqycnB32Jgum/ZZq1W+AEbvLwjNytnl1oJNxgtfjrljYk=,iv:uVRP66mlqKsC39LBPXcGuFk2yHfLF/pi5MxEmO2D1/U=,tag:jUCyJgLIvu9Y5Z+8CTlRvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBVbVVl
            ejZyVTJCUTlwazZ5MlFmZmI1RFIvM0VqeklBSXZnVDdPT2xmTlNFCm1zRmJ4eHlV
            YlUwcWdVZHZEelpuR1hBTG5uM2FNNDFORXY5ZlNIcGZDamsKLS0tIGNKWmo4MzBQ
            dkFQVnpOQTRoVEFsaW5ialBtODZUck5VSmNUaUNXN3N0MU0KMjd/Ci0UBm084nbL
            CTTUJl6Vpx8HDiBprDBGr5u9LuokqC4TDpBbKbND1Po+LvcL0mX5VCpHatK0bPdt
            +wT81Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1pFNzdPRE85ZFRUTElX
            VUkzeWlOY3IxVzQ2bEFkVVNNNzhGb1Q2WEgwCnV3Q2d1Ky92OFhXc3Q3a0wrN1NZ
            d0h5c0ZQVzJidXdYNFRkdUMyTHlDcXMKLS0tIEZtSWxEdGxvaVhBM3BWMVA0T3dM
            cXkzelBqYzZxcnliVGM1MDZjcU1sS3MKMEilOTt5ZlwPUhM8XmQxZhUqe1Fhgrao
            MiT/4xabiEZmw+DVT+8dUuJFblE66K7RldHz3ENqDiUHLpnfmExCJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xqq5gh0k7gcv5cgdu85m4nc0yft4dp9wu62dd4rcfzmwknrc0u9sc3s3cw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUWcvVm1jV2hQVXRxNUJT
            bmliYXU3VG1IUXQraXZldmVjbWIzdXcrMm5vCjd4N0tFZlU1cjF5SnlmVldDQk0y
            MmRqMkp5V1JEdXdYaXl0MldsUkdWNkkKLS0tIGpHV3c3MkZQbUJKdlRPTFdrTTQr
            RlVXT3JVNm43elBNUUNyL2tYZEVKQ2sKgRydvfRfNbK2TYYzT+t7Mt9Apn5rPny8
            tEhN39VWUzxVCP9KwfujC60HdrHpYuia7/UbnCMN76d0CF6avCAXig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gytlmwd26fgj3ddrgl3z0lrufk549f7sc7lzajalxksdqtceqvdqevhf83
    lastmodified: "2026-06-18T12:15:33Z"
    mac: ENC[AES256_GCM,data:NmMfjwsqkEfM2Lacc6oyrM4uSirSw65+i6cbFicU+BTF3YMszauNMvfYYRu72uj/lY9RRwY1Y2MiftM3QkaWXjO0JHQccRupvha4UC47hrAF/QGPy9o3VMR8Sgk1rWCYr4KMkKMs5kqz8tFci8iHEN7pL9y0CPKPMIn24d5Wn3c=,iv:i8HeD3wJG+413SwMBNdx2oj0f6Z3qOYfWbMg0iw4KeM=,tag:PbDnVvmWT1t57GEX9b3Bbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
