cosign:
    private_key: ENC[AES256_GCM,data:EZ5yycJMUJkerzUP4L1piuVvQuBxHs/wDLfmH8MIp19cqyQ5ZHRn1+VhzuhR4bwoARAxtQ39c9trtXufLLKGFK41iraUL7Fh0e6L5HZvIJyAkehpCkYdQeVSlJKoxiInZrUU76MW22gaaJ7xEaNEDLg8Ip8FkZMaGdHNXPcEXjAUtsQE8Mzz614sf4L02RQP5IZyyf5U6Zvm/OHA1AWf5tzUGpNAdpP5uuiIWo9cbIwBYp7a1p6RQJTkXRpM9G2ylZE7dBAJDYRIepmqKZUJf+AYF0RsE7SopmgzWAFBM/zASeDSw1fCyyep/M3HWHypBoULElyptmY/pyaLknE48c6A502wl6uu0NhIcTMfa5Y57J/0rmnjoIDSqFi8Dm4yFd/8e1eVb35CNKre+5ABn/mjhfIrXhdJuLQZp9iqvmCPcwiP1k8pgrCxdHzyxfAOGJ6C8XA/L0hr7vVnVtWa+T6+uiUz0/3gthySu5sGyYQhEgXEFBqlWx7c6KrW9aFQoYxoZ5OiAcr3HRy0cJZtyUgZCRcz7Y7nLmzTFlDd7jskgxw7SwW0FRWZCePHA1xbWq4Sc5+FAsn+OFqbZd9Bs6azBmosBk6zeISfp6TW1unqqsPtCK7FP0e+koB91dL6HxbdNq1ddNzP+fnr+Q2xFgSJVZJ/qjl3blqkk12/odKG7ycH38Z2MYX5d9H1+PfKqQvf+6vzwdQ0Vc+VPfO4L+4g6sDWM6X6rMSTQQS2vLSEYzjGG0AGKSxfXc47xcqx2tW0djRfW4gbXJH0o2tYuWL5B78LgUktN50hHwyf2uA+8eO7DtXAfbFuSExHc4BrEFFALGNZER8IAqZv1hgQNbtlkR20olhH/FCiM/o=,iv:N3uOmG7H4wYmcJRNaGI1D2v8/lSec+urGGpqVW2cW6o=,tag:eiTnpDGGK3UuaKs6mNRUyQ==,type:str]
    password: ENC[AES256_GCM,data:gSLK4b9R361uIwIPtrxJ+4rZsNHvwsgWKcpM3aKLzFY=,iv:rHUdNi1A/VMN7OvWiVpV+VEVCgwkzrDnfANftAyPwJ8=,tag:BR/nsIQVSlFUMCuQt52ZIA==,type:str]
homebrew:
    tap_deploy_key: ENC[AES256_GCM,data:/d71cNSO4jF1kXEJcPwlY5FmQMlDv8/rfft2hu0BpUakvFaTFkQH+Kct5CjlNfuzPuEJKaGx1ML+zRwFYHxOO48ia4gDXu0pAevYF6WYuro+bADlwGRkUxMz1my+9Ft4thit9ytM1ZVqlHRwE+rTlUTGx2tkhafSxZo4o1bs6SOcW/QYULDIJXe8TUueJQ6DPBfakqAfwdiEZxTotUVgNjdB9/m1yG9FqqnX7BBVRWxWFb/QXOOWKASoY7QQjwEoGlsFpihsrYlYGdpaEiVNePYPfnHY3hsijXLfTu7l60nBey9waCONdZt3f/XZErH+A1NPGzavtjcelLJsW1ju84hxwHSyDi5HrIAYEI4qe6LqWTidy4PufXB1F/N6VgQ2XVyDzTOmFOSEiJzV+6PljBjyEwcLiLpe8diMC7fXf695/qFHs7ipvmwB8oSlgg5UElYq/UOhQ0RRDsSBrE2ZC3TrFCGJBY7u3FD1m9MMSCLxirJuAZTsmWtGn6Cdoup7LprFMhFuYJzQD1hrSAVpTWi4MhVjdY0b2Yyy,iv:a+EpyfVQTP5RNzffgnjTtMR2pggWe1URaXD6b0FJ0gE=,tag:55ToguCLX8t+8gyMKmDM/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBsclRr
            djdqWEpYd2E5YVJhcnE4SWcwSHU2K0hVQ21UZUI1UFhJSGZpUEFBCmpqM0NOdnE0
            S0MrTnBudi93eEtmRFNCcnRoRzhUYm84T0hGRjhFL1JsS00KLS0tIFRFeEdPQnBM
            cDJCSi8raWhuL3pXVjdzV1I3cEowL3JacmVTUVJMdk42dHMKBKK+u43X0H7OEX0n
            JVRbaDOMZ5UIPJjOAQRFm/ksNc9EebR5QJ/2T5bSUCIu2nd6eVznp+btrvYDUZDm
            ZrhBmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdzRPK1ZNbWRNY3pJelBt
            WUR1V1JicWhQZWUrYU45cy9GK1hWUmd5UHcwCmRiaEt6WVhsUHdic2RvUGM5NUc4
            a2FiaUwxWStXU0FOYjVOTGFLK2crUk0KLS0tIGN5NUhoOG9ZSi83ZnMwaGJXYTF4
            TGZsMWtKZEdXYTZmQk9LR0JGblBmUUkK/HosF1J/XI6Jwekvzy3wTMAf6oYgaUPz
            N7I59xXmqLSkLid5k17ZhE3RDeYTC3tDDl6hxK4YJs/kMFx8AyV4Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gytlmwd26fgj3ddrgl3z0lrufk549f7sc7lzajalxksdqtceqvdqevhf83
    lastmodified: "2026-06-18T12:15:33Z"
    mac: ENC[AES256_GCM,data:INRC6xjFFkEgPdWzVrAdq/J88ueaSijlssa5kf8jpg1WJ7WZNVYsV/Ln7DyUPVzyBiP+mIARHaAw8w6EKq0SYwnY7+4JejWAmRWFjZTioZOAFt97qx403geB36V920Mi+gH177VagATTBeK/koe7JodG+BC9OmQ1Id1hAU2Qluk=,iv:rPKmo4FHBQQF3tJwV7g/3e1f1ft9dzUdcHmZ8FigAYw=,tag:RUh0FBrNrH9NtjQqxk+crg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
