owner_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>"

semantic_release_age:
  public_key: age1xqq5gh0k7gcv5cgdu85m4nc0yft4dp9wu62dd4rcfzmwknrc0u9sc3s3cw
  github_secret_name: SOPS_AGE_KEY_RELEASE

publish_age:
  public_key: age1gytlmwd26fgj3ddrgl3z0lrufk549f7sc7lzajalxksdqtceqvdqevhf83
  github_secret_name: SOPS_AGE_KEY_PUBLISH

git_signing:
  public_key_openssh: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE8RA7AR2shspsOFJ/T/9KMgErtxoua8+3HlvviIj7Gw dennisrieks@googlemail.com"
  github_secret_name: SEMANTIC_RELEASE_GIT_SIGNING_KEY

cosign:
  public_key_pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE78o2PRsMns0PRbDUq6NXmp9YBrKG
    /xWEEwbM3MTNLRj4oBNJJ6ZL12/0umjufNCwJB+5ENuwVCCAtHbGzpDrLQ==
    -----END PUBLIC KEY-----

homebrew_tap:
  public_key_openssh: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAgaPiEHbpOm4Ou2xG8qB5II+1mvVOJMf93hyWRMrAy hydra-homebrew-tap"
  github_secret_name: HOMEBREW_TAP_DEPLOY_KEY
