renovate:
    token: ENC[AES256_GCM,data:d+0xtns50as2fKjSRJY+0613FPYnJ9pWhejq,iv:XDbn27lU168ZVnTWiYYwhfU+5bWBP0SHzt5Exd2OBoo=,tag:ftcJzGtQSUMh/JdriwTh3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBPNVQy
            S0lkZmFweHVBSEdVaWRWRFpScDVoQTNtNWZHRE1mbkNiWjdMaEZFClh5NFZ3ZFVS
            UzF0aWltSVh1aDdZdnFwQVJIa3pNcko0a3NmUElGQThkNFUKLS0tIEQ4bitRM3Nl
            Z3F2eFVUSUFSN3Q2TlNzb2dFaXBNU2hNbTVVanFPWlpoSncKY68Axe3n1GY2i2TA
            3jXrr12BjimMlsXhzupwyoEivU3NQWpqB59EyNae/rq60XG4nt1+rMLj+u/DhQGe
            gb4H+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
    lastmodified: "2026-06-18T12:03:46Z"
    mac: ENC[AES256_GCM,data:EytzX0/r2v2w5YHAF6TIopqpWpxuMEGnCBP7TiQNbejINNWx+MPSnLxjDhqEdEEaYb7bVaDpTPIM+JOVfAbDRY8mQpfSlen6aWIf8gX/HfE2BEjmOzBdlqaeKMGHl6UM/bHVfTsQApZHKbVBnh2BusOzUhiY638i/LJaBhchsas=,iv:pVnqkqfIIaqQ7uOrPesikOvEGSOKXLsaQ1BByC+BrnY=,tag:8ZSuskyDOU2ZiR4dKgzxtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
