# syntax=docker/dockerfile:1.7

ARG TARGETOS=linux
ARG VERSION=dev
ARG SOPS_VERSION=3.13.1

FROM ghcr.io/getsops/sops:v${SOPS_VERSION} AS sops

FROM alpine:3.24

# BuildKit predefined platform args must be declared inside the stage scope.
ARG TARGETOS=linux
ARG TARGETARCH=amd64

LABEL org.opencontainers.image.version=$VERSION

RUN apk add --no-cache ca-certificates curl git

COPY ${TARGETOS}/${TARGETARCH}/hydra /bin/hydra
COPY --from=sops /usr/local/bin/sops /bin/sops

RUN \
    ln -s /bin/hydra /bin/cosign && \
    ln -s /bin/hydra /bin/helm && \
    ln -s /bin/hydra /bin/yq
