git_signing:
    format: ENC[AES256_GCM,data:WR3h8HbhPUcm6M0=,iv:BNIBI6jo18CBxcVC2gXmcYjGgEhFLwpdBn5q07fMMbM=,tag:hEMXRHZ+TvMRtpluT1zFjA==,type:str]
    private_key: ENC[AES256_GCM,data:LEjLTgrTlZ9Lt4oFgZ3Lq3N4vkLBF/JguSAeCzVzypJv1dz4OK94yrCkZq1DdFu99KZEAgop4YfKkGjR75wrPGmfIbUQlnUJGvREJgOYPbKDecB7pTfvJsSY+d02kVw7ekOPp1hZImSLaxqkacwhgpSXJA5ttD9GgV3sb2Fl9kTKgfVoDoXBPbQkRHi3p0KK5LzByoUPQN1U2kgtTmLowv2Jd9O6csy8zataH3nttF9IKCaL4Ae9OUBc+/39qGYGzndkElcngYcFl9GXPzMQTSxmXPWKt6H3MdOR4gfNiUxLLVsHSO37/ccdplRrmZjB4fRythfzUEEZI9N3X8PyPAeWU8H644UfADaqIvc9qVko0W9LRn7gkl9RJWVw6yW5OkkGaKarmMoxlnv67PaKdIIRUZjzkG4Eq1RpYeGpqnIkxBuoT3wBpUV2A1fFpaz7WTjtUzM8KGLOzNYJlLeHbXyjkT9gdV9gMN7IUYkiSCSpE/jLBH1Tg2gqx4Dh/i7+edZIEYqozyB18qvZUMYer5TblgVJDqbqBxkALtfXWrF5wIYdNTp73SsnV/Et7ws=,iv:WqRjZFCJ/4hvga7Lj9NffSosrx3IwGLlMO8Ir1Uyb68=,tag:UnwGoJx0zCaTmAh6yNVyrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBCSTJz
            VXZrWVVPNWdwMWZRYTN0RDg4K2d3WTV2c0ZnenBMaVdjNmF6MnpFClZMTlh1SGgx
            WXN3U0prOU1oMmJQcG42SU1sd3U1ZUl1ckxDOHNvVTdkQ3MKLS0tIHRzeU1QczVm
            dmRuNEhjckFadSswNytWM0t2ZmFrUVNJWXE5cWdZdzVnODgKueZxG6/K1Lgw3K7Y
            FlElXzw9kw1pnZ1AMox1LU1iq2PTpeWCLvYA0c/aBKBjZnXJLHi7Mcqo5gm6IiVl
            UNicTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U1lpZCtLWUgranc5bXdo
            L2ppTjE2MGZLVThmc0JMTTVaRUxmUHR2NTFvCjdJNER1dHhMQjZqRkM4MTB1T21H
            Yi8rMDlqV3Q5LzZVSkk0K2hTOS9jNkEKLS0tIHFWK3M0VkZUMnluZkwzMzliYVNT
            Nlc2TmVyNmdNamFvQUNYMng1RStFNHcKVREfThj+p23PxcpLxorTfc5osZkAiARl
            /RKmJ0ooCs9359Vszcq7j9/UBcJxDyIClK3FeyWEoRIlqZsD3WrsBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmc2s5w8rfadyvn779mj8lawq8nh97fs4a2tft748xecc8lmgynstj8jus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMVZSMVRGTVdkdDl5aWN3
            cmFjVHhBVkxnU3hZRlNONUVDbTI1d2U5aWswCng5YjNoMXFzUVd2WVphbXdlZ1BI
            cngzOFd6c25XaitoZlQ3d0FjOEo0S1EKLS0tIDkreExDcXR4eC9EV0pNSGRLK0ZY
            WmtqdFcwTXhkYi9Lckx1RmV1SjJhaDAKv5lDQQOhQgVgTHXpLg1lFun0wrqxEQYG
            170idVCfXnWQPhL4BsKX/V2xpJfe/UbBHqGrFxFDqCvEA9bw/I2dwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5kdlgv43ehhngrnukjfc639hk00qa826tzk29k9j97tp9xtwefq3x4ksw
    lastmodified: "2026-06-18T10:02:18Z"
    mac: ENC[AES256_GCM,data:z6FTUadN7h3AaW2kDnyLt/gQuawpAMaigrX8zwgsehQr9oPDPgd/RShL8R2+atVZJ4XWVsAUN2dKRGUMa9GBfv6mQLZv8FDtZEl8Zgb6jbifrPVDUdAjJjEP7oFP7AAThXfGOgxJ6x/eweA5Hel1onNaQoxskar1fhglyEqW2Qo=,iv:69XxxBawtt/5i8l9dYtgLJO8PYkt11osKJFZc4RXK20=,tag:BudoNwBEEQwkDTcYNTkTcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
