renovate:
    token: ENC[AES256_GCM,data:sZqD5DpDnuGnC6syOtPVgS+cMlmiwdXbtJp9S29srsLN8da+vQ6FNz8wwuhITDdx2tO2D14vGYRwwENjBqOPslkOfuXuszUnL/FdhbSvIF3quO39fBCRagOMm+QH,iv:Gx7+XH8H16LIUkz1QYuFaEqJ2XQdbn4HueN+1dhtbZE=,tag:plI0/sA15WQbw2RaHQ0Gfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USB4NjNX
            RnBXazUzVXovblJjcTFhT2lOSVR3Uit4bjg2SDdXVCtDdUpEOTNZCkY2UXZNYSt6
            MjRsc0NIbzBKTjNrdmE0a1M0ZzZTanp4ajhwVU1qeGdINHcKLS0tIDlWM1dSQXNr
            V3dtRzlScnpMbXNFNHdSTCs3NTdybFMzSFhjKzlBNGwyTzQKUk0JKyKsnF7JnMIf
            I+QMusBUoNnxEt3hM8mP/oM3YkQfH9SJ9w1rJ2yGVODN4Uk6gGfRTa14i00LU9SQ
            H70OzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
    lastmodified: "2026-06-08T11:56:02Z"
    mac: ENC[AES256_GCM,data:VGZ8hYrKWzTNqP5YOglyy9CS6uc4y+UV4ymhuukJrrGqxcVFHQagLkerhWnJ+9l/g/6VHdCAQGDHfbliSl1dfKu+rOJcNODIVs6oTmkJ2BgcCYOTpkPV11XgnvCKV8q4jUfb7oShxKebSmUM9n5oKhXIWlNzIXoKRrDGSMTY3G8=,iv:Q5FQ1O8b8NNxJhr93+s5hk73gCB4n197vAWLVRLQc2w=,tag:izt3MX69MwimjxNSWIq3eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
